services:
  decs_locator:
    container_name: decs_locator
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - 8030:8000
    environment:
      - APP_VER=${APP_VER}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
      external: true
