FROM docker.io/bitnami/php-fpm:8.4 as builder

# Install build packages and git
RUN apt update -y && apt install -y git autoconf build-essential

# Install Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash


##########################################################################
FROM docker.io/bitnami/php-fpm:8.4

# Copy configuration
COPY ./docker/php/php-fpm.conf-development /opt/bitnami/php/etc/php-fpm.conf
COPY ./docker/php/php.ini-development /opt/bitnami/php/etc/php.ini

ENV PHP_INI_SCAN_DIR /opt/bitnami/php/lib/inc

# Copy Symfony CLI from builder stage
COPY --from=builder /root/.symfony5/bin/symfony /usr/local/bin/symfony

WORKDIR /app

EXPOSE 8000

CMD ["symfony", "server:start", "--allow-all-ip"]
